

//  ---------- INLCUDED BLOCK: MUX4_32  ---------- 
module MUX4_32 (
  input [31:0] A, B, C, D,
  input [1:0] S,
  output reg [31:0] Z
);
  always @(*) begin
    case (S)
      2'b00: Z <= A;
      2'b01: Z <= B;
      2'b10: Z <= C;
      2'b11: Z <= D;
    endcase
  end
endmodule



//  ---------- INLCUDED BLOCK: MUX2_32  ---------- 
module MUX2_32 (
  input [31:0] A, 
  input [31:0] B, 
  input S, 
  output [31:0] Z
);
  assign Z = (S) ? B : A;
endmodule



//  ---------- INLCUDED BLOCK: REGISTER_FILE  ---------- 
module REGISTER_FILE # (
    parameter p_DATA_MEM_SIZE = 2**10
)(
    input [31:0] i_Data_Rd,
    input [31:0] i_Instruction,
    input i_Write_Enable,
    input i_Clk,
    input i_Rst,
    output [31:0] o_Data_Rs_1,
    output [31:0] o_Data_Rs_2  
);
    /* Constants */
    localparam c_SP_INDEX = 2;
    localparam c_GP_INDEX = 3;
    localparam c_GP_INITIAL_VALUE = 32'h1001_0000;
    localparam c_SP_INITIAL_VALUE = c_GP_INITIAL_VALUE + p_DATA_MEM_SIZE - 4;

    /* Instruction fields */
    wire [4:0] w_Select_Rd = i_Instruction[11:7];
    wire [4:0] w_Select_Rs_1 = i_Instruction[19:15];
    wire [4:0] w_Select_Rs_2 = i_Instruction[24:20];
  
    /* Registers Data */
    reg [31:0] r_Registers [0:31];
  
    integer i;
    always @(posedge i_Clk or posedge i_Rst) begin
        if(i_Rst) begin
            for(i = 0; i < 32; i = i + 1) begin
                case (i)
                    c_SP_INDEX: r_Registers[i] = c_SP_INITIAL_VALUE;
                    c_GP_INDEX: r_Registers[i] = c_GP_INITIAL_VALUE;
                    default:    r_Registers[i] = 32'h0;
                endcase
            end
        end
        else begin 
            if(i_Write_Enable && w_Select_Rd != 5'h0) begin
                r_Registers[w_Select_Rd] = i_Data_Rd;
            end
        end
    end
    
    assign o_Data_Rs_1 = r_Registers[w_Select_Rs_1];

    assign o_Data_Rs_2 = r_Registers[w_Select_Rs_2];

endmodule



//  ---------- INLCUDED BLOCK: PROGRAM_COUNTER  ---------- 
module PROGRAM_COUNTER (
    input [31:0] i_Data,
    input i_Clk,
    input i_Rst,
    output [31:0] o_PC_Output, 
    output [31:0] o_PC_Plus_4
);
    localparam c_PC_INITIAL_VALUE = 32'h0040_0000;

    /* Program Counter (PC) */
    reg [31:0] r_PC_Output;

    always @(posedge i_Clk or posedge i_Rst) begin
        if(i_Rst) begin
            r_PC_Output <= c_PC_INITIAL_VALUE;
        end
        else begin
          	r_PC_Output <= i_Data;
        end
    end

    assign o_PC_Output = r_PC_Output;

    assign o_PC_Plus_4 = r_PC_Output + 4;
endmodule


// Automatically generated by ChipInventor Cloud EDA Tool - 3.15
// Careful: this file (hdl.v) will be automatically replaced
// when you ask tool to generate top Verilog code by clicking
// at BLOCKS button.

module top (

  input wire i_PC_Sel,
  input wire [31:0] i_ALU_output,
  output wire [31:0] o_PC_output,
  input wire [31:0] i_Instruction,
  input wire i_Write_Enable,
  output wire [31:0] o_Data_Rs_1,
  output wire [31:0] o_Data_Rs_2,
  input wire [31:0] i_Memory_Data,
  input wire [1:0] i_Write_Back_Sel,
  input wire i_clk,
  input wire i_rst

);

//Internal Wires
 wire [31:0] w_1;
 wire [31:0] w_2;
 wire [31:0] w_3;

//Instances of Modules
REGISTER_FILE #(.p_DATA_MEM_SIZE(2**10)) blk2116_15 (
         .i_Instruction (i_Instruction [31:0]),
         .i_Write_Enable (i_Write_Enable),
         .o_Data_Rs_1 (o_Data_Rs_1 [31:0]),
         .o_Data_Rs_2 (o_Data_Rs_2[31:0]),
         .i_Clk (i_clk),
         .i_Rst (i_rst),
         .i_Data_Rd (w_1)
     );

PROGRAM_COUNTER blk2117_16 (
         .o_PC_Output (o_PC_output [31:0]),
         .i_Clk (i_clk),
         .i_Rst (i_rst),
         .i_Data (w_2),
         .o_PC_Plus_4 (w_3)
     );

MUX2_32 blk1779_18 (
         .S (i_PC_Sel),
         .B (i_ALU_output [31:0]),
         .Z (w_2),
         .A (w_3)
     );

MUX4_32 blk1778_30 (
         .A (i_ALU_output [31:0]),
         .C (i_Memory_Data [31:0]),
         .D (i_Memory_Data [31:0]),
         .S (i_Write_Back_Sel [1:0]),
         .Z (w_1),
         .B (w_3)
     );


endmodule
